// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -typed -source=service.go -destination=mocks/mock_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	pkg "deblockTest/pkg"
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockEthereumBlockGetter is a mock of EthereumBlockGetter interface.
type MockEthereumBlockGetter struct {
	ctrl     *gomock.Controller
	recorder *MockEthereumBlockGetterMockRecorder
	isgomock struct{}
}

// MockEthereumBlockGetterMockRecorder is the mock recorder for MockEthereumBlockGetter.
type MockEthereumBlockGetterMockRecorder struct {
	mock *MockEthereumBlockGetter
}

// NewMockEthereumBlockGetter creates a new mock instance.
func NewMockEthereumBlockGetter(ctrl *gomock.Controller) *MockEthereumBlockGetter {
	mock := &MockEthereumBlockGetter{ctrl: ctrl}
	mock.recorder = &MockEthereumBlockGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthereumBlockGetter) EXPECT() *MockEthereumBlockGetterMockRecorder {
	return m.recorder
}

// BlockByNumber mocks base method.
func (m *MockEthereumBlockGetter) BlockByNumber(ctx context.Context, number *big.Int) (*types.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockByNumber", ctx, number)
	ret0, _ := ret[0].(*types.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockByNumber indicates an expected call of BlockByNumber.
func (mr *MockEthereumBlockGetterMockRecorder) BlockByNumber(ctx, number any) *MockEthereumBlockGetterBlockByNumberCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockByNumber", reflect.TypeOf((*MockEthereumBlockGetter)(nil).BlockByNumber), ctx, number)
	return &MockEthereumBlockGetterBlockByNumberCall{Call: call}
}

// MockEthereumBlockGetterBlockByNumberCall wrap *gomock.Call
type MockEthereumBlockGetterBlockByNumberCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEthereumBlockGetterBlockByNumberCall) Return(arg0 *types.Block, arg1 error) *MockEthereumBlockGetterBlockByNumberCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEthereumBlockGetterBlockByNumberCall) Do(f func(context.Context, *big.Int) (*types.Block, error)) *MockEthereumBlockGetterBlockByNumberCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEthereumBlockGetterBlockByNumberCall) DoAndReturn(f func(context.Context, *big.Int) (*types.Block, error)) *MockEthereumBlockGetterBlockByNumberCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BlockNumber mocks base method.
func (m *MockEthereumBlockGetter) BlockNumber(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockNumber", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockNumber indicates an expected call of BlockNumber.
func (mr *MockEthereumBlockGetterMockRecorder) BlockNumber(ctx any) *MockEthereumBlockGetterBlockNumberCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockNumber", reflect.TypeOf((*MockEthereumBlockGetter)(nil).BlockNumber), ctx)
	return &MockEthereumBlockGetterBlockNumberCall{Call: call}
}

// MockEthereumBlockGetterBlockNumberCall wrap *gomock.Call
type MockEthereumBlockGetterBlockNumberCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEthereumBlockGetterBlockNumberCall) Return(arg0 uint64, arg1 error) *MockEthereumBlockGetterBlockNumberCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEthereumBlockGetterBlockNumberCall) Do(f func(context.Context) (uint64, error)) *MockEthereumBlockGetterBlockNumberCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEthereumBlockGetterBlockNumberCall) DoAndReturn(f func(context.Context) (uint64, error)) *MockEthereumBlockGetterBlockNumberCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPublisher) Publish(ctx context.Context, msgs []pkg.TxMessage) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", ctx, msgs)
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(ctx, msgs any) *MockPublisherPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisher)(nil).Publish), ctx, msgs)
	return &MockPublisherPublishCall{Call: call}
}

// MockPublisherPublishCall wrap *gomock.Call
type MockPublisherPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublisherPublishCall) Return() *MockPublisherPublishCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPublisherPublishCall) Do(f func(context.Context, []pkg.TxMessage)) *MockPublisherPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublisherPublishCall) DoAndReturn(f func(context.Context, []pkg.TxMessage)) *MockPublisherPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockUserGetter is a mock of UserGetter interface.
type MockUserGetter struct {
	ctrl     *gomock.Controller
	recorder *MockUserGetterMockRecorder
	isgomock struct{}
}

// MockUserGetterMockRecorder is the mock recorder for MockUserGetter.
type MockUserGetterMockRecorder struct {
	mock *MockUserGetter
}

// NewMockUserGetter creates a new mock instance.
func NewMockUserGetter(ctrl *gomock.Controller) *MockUserGetter {
	mock := &MockUserGetter{ctrl: ctrl}
	mock.recorder = &MockUserGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserGetter) EXPECT() *MockUserGetterMockRecorder {
	return m.recorder
}

// GetUserID mocks base method.
func (m *MockUserGetter) GetUserID(addr common.Address) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID", addr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockUserGetterMockRecorder) GetUserID(addr any) *MockUserGetterGetUserIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockUserGetter)(nil).GetUserID), addr)
	return &MockUserGetterGetUserIDCall{Call: call}
}

// MockUserGetterGetUserIDCall wrap *gomock.Call
type MockUserGetterGetUserIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserGetterGetUserIDCall) Return(arg0 string, arg1 bool) *MockUserGetterGetUserIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserGetterGetUserIDCall) Do(f func(common.Address) (string, bool)) *MockUserGetterGetUserIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserGetterGetUserIDCall) DoAndReturn(f func(common.Address) (string, bool)) *MockUserGetterGetUserIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
	isgomock struct{}
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// LoadCheckpoint mocks base method.
func (m *MockState) LoadCheckpoint() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCheckpoint")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// LoadCheckpoint indicates an expected call of LoadCheckpoint.
func (mr *MockStateMockRecorder) LoadCheckpoint() *MockStateLoadCheckpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCheckpoint", reflect.TypeOf((*MockState)(nil).LoadCheckpoint))
	return &MockStateLoadCheckpointCall{Call: call}
}

// MockStateLoadCheckpointCall wrap *gomock.Call
type MockStateLoadCheckpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateLoadCheckpointCall) Return(arg0 uint64) *MockStateLoadCheckpointCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateLoadCheckpointCall) Do(f func() uint64) *MockStateLoadCheckpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateLoadCheckpointCall) DoAndReturn(f func() uint64) *MockStateLoadCheckpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveCheckpoint mocks base method.
func (m *MockState) SaveCheckpoint(blockNum uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCheckpoint", blockNum)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCheckpoint indicates an expected call of SaveCheckpoint.
func (mr *MockStateMockRecorder) SaveCheckpoint(blockNum any) *MockStateSaveCheckpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCheckpoint", reflect.TypeOf((*MockState)(nil).SaveCheckpoint), blockNum)
	return &MockStateSaveCheckpointCall{Call: call}
}

// MockStateSaveCheckpointCall wrap *gomock.Call
type MockStateSaveCheckpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateSaveCheckpointCall) Return(arg0 error) *MockStateSaveCheckpointCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateSaveCheckpointCall) Do(f func(uint64) error) *MockStateSaveCheckpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateSaveCheckpointCall) DoAndReturn(f func(uint64) error) *MockStateSaveCheckpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
